set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports in_a[7]]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports in_a[6]]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports in_a[5]]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports in_a[4]]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports in_a[3]]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports in_a[2]]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33} [get_ports in_a[1]]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports in_a[0]]

set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports in_b[7]]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports in_b[6]]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports in_b[5]]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports in_b[4]]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports in_b[3]]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports in_b[2]]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports in_b[1]]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports in_b[0]]

set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33} [get_ports op[2]]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports op[1]]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports op[0]]

set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports fnd_digit[7]]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports fnd_digit[6]]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports fnd_digit[5]]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports fnd_digit[4]]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports fnd_digit[3]]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports fnd_digit[2]]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports fnd_digit[1]]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports fnd_digit[0]]

set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports fnd_value[7]]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports fnd_value[6]]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33} [get_ports fnd_value[5]]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports fnd_value[4]]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports fnd_value[3]]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports fnd_value[2]]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports fnd_value[1]]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports fnd_value[0]]

set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports reset]
