set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33}     [get_ports DI[9]]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33}     [get_ports DI[8]]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33}     [get_ports DI[7]]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33}     [get_ports DI[6]]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33}     [get_ports DI[5]]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33}     [get_ports DI[4]]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33}     [get_ports DI[3]]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33}     [get_ports DI[2]]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33}    [get_ports DI[1]]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33}    [get_ports DI[0]]

set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33}    [get_ports en]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33}    [get_ports clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33}    [get_ports reset]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVCMOS33}    [get_ports reset_o]

set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33}    [get_ports DO[9]]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS33}   [get_ports DO[8]]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVCMOS33}   [get_ports DO[7]]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33}    [get_ports DO[6]]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33}    [get_ports DO[5]]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS33}   [get_ports DO[4]]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33}    [get_ports DO[3]]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVCMOS33}   [get_ports DO[2]]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS33}   [get_ports DO[1]]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33}    [get_ports DO[0]]
