set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports in[9]]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports in[8]]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports in[7]]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports in[6]]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports in[5]]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports in[4]]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33} [get_ports in[3]]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports in[2]]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports in[1]]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports in[0]]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports reset]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports out]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets reset_IBUF]
